#!/usr/bin/env python3
"""
Cross-schema validation: apply the pre-trained compaction model to TPC-H tables.

Pipeline:
    1. Extract 17 observable metadata features from each TPC-H Iceberg table
    2. Run compaction (rewrite_data_files) and record before/after metrics
    3. Derive labels (needs_compaction, file_reduction_ratio)
    4. Load the XGBoost models trained on synthetic UUID data
    5. Predict on TPC-H features and compare with actual labels
    6. Output generalization metrics

This script is self-contained: it reuses the same feature-extraction
logic as extract.py and the same compaction procedure as compact.py,
but operates on TPC-H tables generated by tpch_gen.py.

Usage:
    python code/tpch_validate.py
    python code/tpch_validate.py --warehouse /mnt/data/tpch_warehouse
    python code/tpch_validate.py --skip-compact   # reuse prior compaction
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from sklearn.metrics import (accuracy_score, classification_report, f1_score,
                             mean_absolute_error, mean_squared_error,
                             precision_score, r2_score, recall_score,
                             roc_auc_score)
from xgboost import XGBClassifier, XGBRegressor

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tpch_gen import TpchConfig, full_tpch_grid  # noqa: E402

LOG = logging.getLogger("tpch_validate")

# ── Defaults ────────────────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WAREHOUSE = "/mnt/data/tpch_warehouse"
CATALOG = "local"
DATABASE = "tpch"

# Iceberg compaction settings (identical to compact.py)
REWRITE_TARGET_BYTES = 128 * 1024 * 1024   # 128 MB
COMPACTION_MIN_BYTES = 96 * 1024 * 1024     # 96 MB  (75% of target)

# The 17 observable features the model was trained on
FEATURE_COLUMNS = [
    "file_count",
    "total_size_bytes",
    "avg_file_size_bytes",
    "min_file_size_bytes",
    "max_file_size_bytes",
    "stddev_file_size_bytes",
    "total_records",
    "avg_records_per_file",
    "num_partitions_actual",
    "avg_files_per_partition",
    "max_files_per_partition",
    "min_files_per_partition",
    "stddev_files_per_partition",
    "num_snapshots",
    "small_file_ratio",
    "file_size_cv",
    "files_per_partition_cv",
]


# ── Spark session ───────────────────────────────────────────────────────────

def get_spark(warehouse: str, app_name: str = "tpch-validate") -> SparkSession:
    return (
        SparkSession.builder.master("local[*]")
        .appName(app_name)
        .config("spark.driver.memory", "12g")
        .config(
            "spark.sql.extensions",
            "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions",
        )
        .config(f"spark.sql.catalog.{CATALOG}", "org.apache.iceberg.spark.SparkCatalog")
        .config(f"spark.sql.catalog.{CATALOG}.type", "hadoop")
        .config(f"spark.sql.catalog.{CATALOG}.warehouse", warehouse)
        .config("spark.sql.shuffle.partitions", "4")
        .config("spark.sql.iceberg.vectorization.enabled", "false")
        .getOrCreate()
    )


# ── Feature extraction ──────────────────────────────────────────────────────

def _fqn(table_name: str) -> str:
    return f"{CATALOG}.{DATABASE}.{table_name}"


def table_exists(spark: SparkSession, table_name: str) -> bool:
    try:
        spark.sql(f"SELECT 1 FROM {_fqn(table_name)} LIMIT 1").collect()
        return True
    except Exception:
        return False


def extract_features(spark: SparkSession, cfg: TpchConfig) -> dict[str, Any]:
    """Extract 17 observable metadata features from one TPC-H Iceberg table."""
    table_name = cfg.iceberg_table_name
    fqn = _fqn(table_name)
    t0 = time.time()

    # ── File-level features
    files_df = spark.sql(f"SELECT * FROM {fqn}.files")
    file_stats = files_df.agg(
        F.count("*").alias("file_count"),
        F.sum("file_size_in_bytes").alias("total_size_bytes"),
        F.avg("file_size_in_bytes").alias("avg_file_size_bytes"),
        F.min("file_size_in_bytes").alias("min_file_size_bytes"),
        F.max("file_size_in_bytes").alias("max_file_size_bytes"),
        F.stddev("file_size_in_bytes").alias("stddev_file_size_bytes"),
        F.sum("record_count").alias("total_records"),
        F.avg("record_count").alias("avg_records_per_file"),
    ).collect()[0]

    file_count = file_stats["file_count"]
    total_size = file_stats["total_size_bytes"] or 0
    avg_file_size = file_stats["avg_file_size_bytes"] or 0
    min_file_size = file_stats["min_file_size_bytes"] or 0
    max_file_size = file_stats["max_file_size_bytes"] or 0
    stddev_file_size = file_stats["stddev_file_size_bytes"] or 0
    total_records = file_stats["total_records"] or 0
    avg_records = file_stats["avg_records_per_file"] or 0

    # ── Partition-level features
    if cfg.num_partitions > 1:
        part_stats_df = (
            files_df
            .select(F.expr("partition.part_key").alias("part_key"))
            .groupBy("part_key")
            .agg(F.count("*").alias("files_in_part"))
        )
        part_agg = part_stats_df.agg(
            F.count("*").alias("num_partitions_actual"),
            F.avg("files_in_part").alias("avg_files_per_partition"),
            F.max("files_in_part").alias("max_files_per_partition"),
            F.min("files_in_part").alias("min_files_per_partition"),
            F.stddev("files_in_part").alias("stddev_files_per_partition"),
        ).collect()[0]

        num_parts_actual = part_agg["num_partitions_actual"]
        avg_files_per_part = part_agg["avg_files_per_partition"] or 0
        max_files_per_part = part_agg["max_files_per_partition"] or 0
        min_files_per_part = part_agg["min_files_per_partition"] or 0
        stddev_files_per_part = part_agg["stddev_files_per_partition"] or 0
    else:
        num_parts_actual = 1
        avg_files_per_part = float(file_count)
        max_files_per_part = file_count
        min_files_per_part = file_count
        stddev_files_per_part = 0.0

    # ── Snapshot features
    num_snapshots = spark.sql(f"SELECT * FROM {fqn}.snapshots").count()

    # ── Derived features
    if file_count > 0:
        small_file_count = files_df.filter(
            F.col("file_size_in_bytes") < COMPACTION_MIN_BYTES
        ).count()
        small_file_ratio = small_file_count / file_count
    else:
        small_file_ratio = 0.0

    file_size_cv = (stddev_file_size / avg_file_size) if avg_file_size > 0 else 0.0
    files_per_part_cv = (
        (stddev_files_per_part / avg_files_per_part)
        if avg_files_per_part > 0
        else 0.0
    )

    elapsed = time.time() - t0
    LOG.info(
        "  extract %s: %d files, %.1f MB, cv=%.2f, small=%.2f (%.1fs)",
        table_name, file_count, total_size / 1e6, file_size_cv,
        small_file_ratio, elapsed,
    )

    return {
        "config_id": cfg.config_id,
        "tpch_table": cfg.tpch_table,
        "file_count": file_count,
        "total_size_bytes": int(total_size),
        "avg_file_size_bytes": round(avg_file_size, 2),
        "min_file_size_bytes": int(min_file_size),
        "max_file_size_bytes": int(max_file_size),
        "stddev_file_size_bytes": round(stddev_file_size, 2),
        "total_records": int(total_records),
        "avg_records_per_file": round(avg_records, 2),
        "num_partitions_actual": num_parts_actual,
        "avg_files_per_partition": round(avg_files_per_part, 2),
        "max_files_per_partition": int(max_files_per_part),
        "min_files_per_partition": int(min_files_per_part),
        "stddev_files_per_partition": round(stddev_files_per_part, 2),
        "num_snapshots": num_snapshots,
        "small_file_ratio": round(small_file_ratio, 4),
        "file_size_cv": round(file_size_cv, 4),
        "files_per_partition_cv": round(files_per_part_cv, 4),
    }


# ── Compaction ──────────────────────────────────────────────────────────────

def compact_table(spark: SparkSession, cfg: TpchConfig) -> dict[str, Any]:
    """Run rewrite_data_files on one TPC-H table and return before/after metrics."""
    table_name = cfg.iceberg_table_name
    fqn = _fqn(table_name)

    t0 = time.time()
    result_df = spark.sql(f"""
        CALL {CATALOG}.system.rewrite_data_files(
            table => '{DATABASE}.{table_name}',
            options => map(
                'target-file-size-bytes', '{REWRITE_TARGET_BYTES}',
                'min-file-size-bytes',    '{int(REWRITE_TARGET_BYTES * 0.75)}',
                'max-file-size-bytes',    '{int(REWRITE_TARGET_BYTES * 1.8)}'
            )
        )
    """)
    result_row = result_df.collect()[0]
    duration = time.time() - t0

    rewritten = result_row["rewritten_data_files_count"]
    added = result_row["added_data_files_count"]

    # After-compaction stats
    after_row = (
        spark.sql(f"SELECT * FROM {fqn}.files")
        .agg(
            F.count("*").alias("file_count"),
            F.sum("file_size_in_bytes").alias("total_size_bytes"),
            F.avg("file_size_in_bytes").alias("avg_file_size_bytes"),
        )
        .collect()[0]
    )

    LOG.info(
        "  compact %s: rewritten=%d, added=%d, after_files=%d (%.1fs)",
        table_name, rewritten, added, after_row["file_count"], duration,
    )

    return {
        "config_id": cfg.config_id,
        "after_file_count": after_row["file_count"],
        "after_total_size_bytes": int(after_row["total_size_bytes"] or 0),
        "after_avg_file_size_bytes": round(after_row["avg_file_size_bytes"] or 0, 2),
        "rewritten_data_files_count": rewritten,
        "added_data_files_count": added,
        "compaction_duration_s": round(duration, 2),
    }


# ── Label derivation ───────────────────────────────────────────────────────

def derive_labels(features: dict, compaction: dict) -> dict:
    """Compute needs_compaction and file_reduction_ratio."""
    needs = 1 if compaction["rewritten_data_files_count"] > 0 else 0
    fc_before = features["file_count"]
    fc_after = compaction["after_file_count"]
    frr = max(0.0, (fc_before - fc_after) / fc_before) if fc_before > 0 else 0.0
    return {
        "needs_compaction": needs,
        "file_reduction_ratio": round(frr, 6),
    }


# ── Model loading & prediction ─────────────────────────────────────────────

def load_models(out_dir: Path) -> tuple[XGBClassifier, XGBRegressor]:
    clf = XGBClassifier()
    clf.load_model(str(out_dir / "model_clf.json"))
    reg = XGBRegressor()
    reg.load_model(str(out_dir / "model_reg.json"))
    return clf, reg


def evaluate(
    df: pd.DataFrame,
    clf: XGBClassifier,
    reg: XGBRegressor,
) -> dict[str, Any]:
    """Run predictions and compute generalization metrics."""
    X = df[FEATURE_COLUMNS].copy()
    y_clf_true = df["needs_compaction"]
    y_reg_true = df["file_reduction_ratio"]

    # Classification
    y_clf_pred = clf.predict(X)
    y_clf_prob = clf.predict_proba(X)[:, 1]

    clf_metrics = {
        "accuracy": float(accuracy_score(y_clf_true, y_clf_pred)),
        "precision": float(precision_score(y_clf_true, y_clf_pred, zero_division=0)),
        "recall": float(recall_score(y_clf_true, y_clf_pred, zero_division=0)),
        "f1": float(f1_score(y_clf_true, y_clf_pred, zero_division=0)),
    }
    # ROC AUC requires both classes present
    if y_clf_true.nunique() > 1:
        clf_metrics["roc_auc"] = float(roc_auc_score(y_clf_true, y_clf_prob))
    else:
        clf_metrics["roc_auc"] = None

    LOG.info("=== Classification (needs_compaction) ===")
    for k, v in clf_metrics.items():
        LOG.info("  %-18s %s", k, f"{v:.4f}" if v is not None else "N/A")
    LOG.info("\n%s", classification_report(
        y_clf_true, y_clf_pred, labels=[0, 1],
        target_names=["no_compact", "compact"],
        zero_division=0,
    ))

    # Regression
    y_reg_pred = reg.predict(X)

    reg_metrics = {
        "rmse": float(np.sqrt(mean_squared_error(y_reg_true, y_reg_pred))),
        "mae": float(mean_absolute_error(y_reg_true, y_reg_pred)),
        "r2": float(r2_score(y_reg_true, y_reg_pred)),
    }

    LOG.info("=== Regression (file_reduction_ratio) ===")
    for k, v in reg_metrics.items():
        LOG.info("  %-18s %.4f", k, v)

    # Threshold baseline 1: small_file_ratio > 0
    y_thresh_sfr = (df["small_file_ratio"] > 0).astype(int)
    thresh_sfr_metrics = {
        "accuracy": float(accuracy_score(y_clf_true, y_thresh_sfr)),
        "precision": float(precision_score(y_clf_true, y_thresh_sfr, zero_division=0)),
        "recall": float(recall_score(y_clf_true, y_thresh_sfr, zero_division=0)),
        "f1": float(f1_score(y_clf_true, y_thresh_sfr, zero_division=0)),
    }
    LOG.info("=== Threshold baseline (small_file_ratio > 0) ===")
    for k, v in thresh_sfr_metrics.items():
        LOG.info("  %-18s %.4f", k, v)

    # Threshold baseline 2: max_files_per_partition > 4
    y_thresh_k4 = (df["max_files_per_partition"] > 4).astype(int)
    thresh_k4_metrics = {
        "accuracy": float(accuracy_score(y_clf_true, y_thresh_k4)),
        "precision": float(precision_score(y_clf_true, y_thresh_k4, zero_division=0)),
        "recall": float(recall_score(y_clf_true, y_thresh_k4, zero_division=0)),
        "f1": float(f1_score(y_clf_true, y_thresh_k4, zero_division=0)),
    }
    LOG.info("=== Threshold baseline (max_files_per_partition > 4) ===")
    for k, v in thresh_k4_metrics.items():
        LOG.info("  %-18s %.4f", k, v)

    # Majority-class baseline (always predict needs_compaction=1)
    y_majority = pd.Series(1, index=y_clf_true.index)
    majority_metrics = {
        "accuracy": float(accuracy_score(y_clf_true, y_majority)),
        "precision": float(precision_score(y_clf_true, y_majority, zero_division=0)),
        "recall": float(recall_score(y_clf_true, y_majority, zero_division=0)),
        "f1": float(f1_score(y_clf_true, y_majority, zero_division=0)),
    }
    LOG.info("=== Majority-class baseline (always compact) ===")
    for k, v in majority_metrics.items():
        LOG.info("  %-18s %.4f", k, v)

    # Per-table-type breakdown
    per_table = {}
    for tbl in df["tpch_table"].unique():
        mask = df["tpch_table"] == tbl
        sub = df[mask]
        X_sub = sub[FEATURE_COLUMNS]
        y_true_sub = sub["needs_compaction"]
        y_pred_sub = clf.predict(X_sub)
        y_reg_true_sub = sub["file_reduction_ratio"]
        y_reg_pred_sub = reg.predict(X_sub)

        per_table[tbl] = {
            "n": int(mask.sum()),
            "clf_accuracy": float(accuracy_score(y_true_sub, y_pred_sub)),
            "clf_f1": float(f1_score(y_true_sub, y_pred_sub, zero_division=0)),
            "reg_r2": float(r2_score(y_reg_true_sub, y_reg_pred_sub))
                if y_reg_true_sub.std() > 0 else None,
            "reg_rmse": float(np.sqrt(mean_squared_error(y_reg_true_sub, y_reg_pred_sub))),
        }

    LOG.info("=== Per-table breakdown ===")
    for tbl, m in sorted(per_table.items()):
        LOG.info(
            "  %-10s n=%3d  acc=%.3f  f1=%.3f  R²=%s  RMSE=%.4f",
            tbl, m["n"], m["clf_accuracy"], m["clf_f1"],
            f"{m['reg_r2']:.3f}" if m["reg_r2"] is not None else "N/A",
            m["reg_rmse"],
        )

    return {
        "n_tables": len(df),
        "class_balance": {
            "needs_compaction_1": int(y_clf_true.sum()),
            "needs_compaction_0": int(len(y_clf_true) - y_clf_true.sum()),
        },
        "classifier": clf_metrics,
        "regressor": reg_metrics,
        "threshold_baseline_sfr": thresh_sfr_metrics,
        "threshold_baseline_k4": thresh_k4_metrics,
        "majority_class_baseline": majority_metrics,
        "per_table": per_table,
    }


# ── CLI ─────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Validate compaction model on TPC-H tables"
    )
    p.add_argument("--warehouse", type=str, default=DEFAULT_WAREHOUSE)
    p.add_argument("--model-dir", type=Path, default=ROOT / "data",
                   help="Directory containing model_clf.json and model_reg.json")
    p.add_argument("--out-dir", type=Path, default=ROOT / "data" / "tpch",
                   help="Directory for TPC-H validation outputs")
    p.add_argument("--grid-csv", type=str, default="code/tpch_grid.csv",
                   help="Grid CSV from tpch_gen.py")
    p.add_argument("--skip-compact", action="store_true",
                   help="Skip compaction (reuse prior results)")
    p.add_argument("--sample", type=int, default=0,
                   help="Validate only N random tables")
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args()


def load_configs_from_csv(csv_path: Path) -> list[TpchConfig]:
    """Load TpchConfig objects from the grid CSV."""
    configs: list[TpchConfig] = []
    with csv_path.open() as f:
        for row in csv.DictReader(f):
            configs.append(TpchConfig(
                tpch_table=row["tpch_table"],
                num_rows=int(row["num_rows"]),
                num_columns=int(row["num_columns"]),
                num_partitions=int(row["num_partitions"]),
                file_size_target_kb=int(row["file_size_target_kb"]),
                num_write_batches=int(row["num_write_batches"]),
                num_writers=int(row["num_writers"]),
            ))
    return configs


def main() -> int:
    args = parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)-5s  %(message)s",
    )

    # ── Load grid ───────────────────────────────────────────────────────
    grid_path = Path(args.grid_csv)
    if grid_path.exists():
        configs = load_configs_from_csv(grid_path)
        LOG.info("Loaded %d configs from %s", len(configs), grid_path)
    else:
        configs = full_tpch_grid()
        LOG.info("Grid CSV not found; using full_tpch_grid() (%d configs)", len(configs))

    if args.sample > 0:
        import random
        rng = random.Random(args.seed)
        configs = rng.sample(configs, min(args.sample, len(configs)))
        LOG.info("Sampled %d configs", len(configs))

    # ── Output directory ────────────────────────────────────────────────
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    features_path = out_dir / "tpch_features.csv"
    compaction_path = out_dir / "tpch_compaction.csv"
    dataset_path = out_dir / "tpch_dataset.csv"
    metrics_path = out_dir / "tpch_validation_metrics.json"

    # ── Check for prior results ─────────────────────────────────────────
    have_features = features_path.exists()
    have_compaction = compaction_path.exists() and args.skip_compact

    # ── Phase 1: Extract features ───────────────────────────────────────
    LOG.info("=== Phase 1: Feature extraction ===")
    spark = get_spark(args.warehouse)

    feature_rows: list[dict[str, Any]] = []
    skipped = 0
    failed_extract = 0

    try:
        for i, cfg in enumerate(configs, 1):
            LOG.info("[%d/%d] %s", i, len(configs), cfg.iceberg_table_name)
            if not table_exists(spark, cfg.iceberg_table_name):
                LOG.warning("  SKIP (table does not exist)")
                skipped += 1
                continue
            try:
                feat = extract_features(spark, cfg)
                feature_rows.append(feat)
            except Exception:
                LOG.exception("FAILED extract %s", cfg.iceberg_table_name)
                failed_extract += 1

        LOG.info(
            "Extracted: %d  |  Skipped: %d  |  Failed: %d",
            len(feature_rows), skipped, failed_extract,
        )

        if not feature_rows:
            LOG.error("No features extracted. Did you run tpch_gen.py first?")
            return 1

        # Write features CSV
        feat_fields = ["config_id", "tpch_table"] + FEATURE_COLUMNS
        with features_path.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=feat_fields)
            writer.writeheader()
            for r in feature_rows:
                writer.writerow(r)
        LOG.info("Features written to %s", features_path)

        # ── Phase 2: Compaction ─────────────────────────────────────────
        if args.skip_compact and compaction_path.exists():
            LOG.info("=== Phase 2: SKIPPED (--skip-compact) ===")
        else:
            LOG.info("=== Phase 2: Compaction ===")
            # Need to re-get spark with compaction config
            spark.stop()
            spark = get_spark(args.warehouse, app_name="tpch-compact")

            compact_rows: list[dict[str, Any]] = []
            failed_compact = 0

            # Build lookup of configs that had features extracted
            valid_ids = {r["config_id"] for r in feature_rows}
            valid_configs = [c for c in configs if c.config_id in valid_ids]

            for i, cfg in enumerate(valid_configs, 1):
                LOG.info("[%d/%d] compact %s", i, len(valid_configs), cfg.iceberg_table_name)
                try:
                    comp = compact_table(spark, cfg)
                    compact_rows.append(comp)
                except Exception:
                    LOG.exception("FAILED compact %s", cfg.iceberg_table_name)
                    failed_compact += 1

            LOG.info("Compacted: %d  |  Failed: %d", len(compact_rows), failed_compact)

            if not compact_rows:
                LOG.error("No tables compacted successfully.")
                return 1

            # Write compaction CSV
            comp_fields = [
                "config_id", "after_file_count", "after_total_size_bytes",
                "after_avg_file_size_bytes", "rewritten_data_files_count",
                "added_data_files_count", "compaction_duration_s",
            ]
            with compaction_path.open("w", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=comp_fields)
                writer.writeheader()
                for r in compact_rows:
                    writer.writerow(r)
            LOG.info("Compaction results written to %s", compaction_path)

    finally:
        spark.stop()

    # ── Phase 3: Build labelled dataset ─────────────────────────────────
    LOG.info("=== Phase 3: Build dataset ===")
    feat_df = pd.read_csv(features_path)
    comp_df = pd.read_csv(compaction_path)
    merged = feat_df.merge(comp_df, on="config_id", how="inner")

    merged["needs_compaction"] = (merged["rewritten_data_files_count"] > 0).astype(int)
    merged["file_reduction_ratio"] = (
        (merged["file_count"] - merged["after_file_count"]) / merged["file_count"]
    ).clip(lower=0.0)

    merged.to_csv(dataset_path, index=False)
    LOG.info("TPC-H dataset: %d rows → %s", len(merged), dataset_path)
    LOG.info(
        "Label balance: needs_compaction=1: %d (%.1f%%), 0: %d (%.1f%%)",
        merged["needs_compaction"].sum(),
        100 * merged["needs_compaction"].mean(),
        len(merged) - merged["needs_compaction"].sum(),
        100 * (1 - merged["needs_compaction"].mean()),
    )

    # ── Phase 4: Load model & evaluate ──────────────────────────────────
    LOG.info("=== Phase 4: Model evaluation ===")
    clf, reg = load_models(args.model_dir)
    LOG.info("Loaded models from %s", args.model_dir)

    results = evaluate(merged, clf, reg)

    # Save metrics
    metrics_path.write_text(json.dumps(results, indent=2))
    LOG.info("Validation metrics saved to %s", metrics_path)

    # ── Summary ─────────────────────────────────────────────────────────
    LOG.info("=" * 60)
    LOG.info("CROSS-SCHEMA VALIDATION SUMMARY")
    LOG.info("=" * 60)
    LOG.info("Tables validated: %d", results["n_tables"])
    LOG.info("Classifier  — Accuracy: %.3f  F1: %.3f",
             results["classifier"]["accuracy"], results["classifier"]["f1"])
    LOG.info("Regressor   — R²: %.3f  RMSE: %.4f",
             results["regressor"]["r2"], results["regressor"]["rmse"])
    LOG.info("Threshold   — Accuracy: %.3f  F1: %.3f",
             results["threshold_baseline"]["accuracy"],
             results["threshold_baseline"]["f1"])
    LOG.info("=" * 60)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
